

service: finder-backend

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1


functions:
  pharmacies:
    handler: handler.pharmacies
    environment:
      DB_HOST: ${opt:DB_HOST}
      DB_USER: ${opt:DB_USER}
      DB_PASSWORD: ${opt:DB_PASSWORD}
    events:
      - http:
          path: pharmacies
          method: get
          cors: true
      - http:
          path: pharmacies
          method: post
          cors: true
      # - http: 
      #     path: pharmacies/{id}
      #     method: put
      #     cors: true
      # - http:
      #     path: pharmacies/{id}
      #     method: delete
      #     cors: true


